Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace MADIVE.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "Invalid value for price")]
        public double Price { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }

        [Range(0, int.MaxValue, ErrorMessage="Invalid value for quantity")]
        public int Quantity { get; set; }
    }
}

Controllers/CartController.cs
using MADIVE.ADL;
using MADIVE.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MADIVE.Controllers
{
    public class CartController : Controller
    {
        MadiveContext _db = new MadiveContext();
      
        // GET: Cart
        // /Cart
        public ActionResult Index(int page = 1)
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];

            // Get sum price of all products
            ViewBag.totalPrice = cart.Sum(p => p.Quantity * p.Price);
            ViewBag.numOfItem = cart.Count();

            // Display just 4 items per page
            var models = cart.ToPagedList(page, 4);
            ViewBag.max = models.PageCount;
            ViewBag.page = models.PageNumber;

            return View(models);
        }

        /// <summary>
        /// Update the current items in cart when
        /// users update it
        /// </summary>
        /// <param name="id">the product id</param>
        /// <param name="quantity">the quantity of the product</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(int id, int quantity)
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];

            if (quantity == 0)
            {
                cart.RemoveAll(p => p.Id == id);
            }
            else
            {
                var updateItem = cart.Find(p => p.Id == id);
                updateItem.Quantity = quantity;
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        /// <summary>
        /// Display a quick preview of cart for last 5 items
        /// when users hover on the cart icon 
        /// </summary>
        /// <returns>Partial view with a list of 5 items in cart</returns>
        public ActionResult GetPreviewItemsInCart()
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>) Session["cart"];

            ViewBag.numOfItem = cart.Count();
            ViewBag.totalPrice = 0;
            foreach (var item in cart)
            {
                ViewBag.totalPrice += item.Price * item.Quantity;
            }
            
            // Return the partial view along with just 5 last items in cart
            return PartialView("~/Views/Cart/_PreviewCart.cshtml", cart.Take(4).ToList());
        }

        /// <summary>
        /// Add an item or update the existing item in Cart
        /// </summary>
        /// <param name="Id">The Id of Product</param>
        /// <param name="quantity">The number of product to add</param>
        /// <returns>Json object contains the items in cart if the request is AJAX</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                Session["cart"] = new List<Product>();
            }

            var cart = (List<Product>)Session["cart"];
            var total = 0.0;

            var product = cart.Find(p => p.Id == id);
            // Update the quantity inside the session
            // in the case the product was in cart
            if (product != null)
            {
                if(quantity > 0)
                {
                    product.Quantity = quantity;
                }
                // Remove the item from cart if the quantity = 0
                else
                {
                    cart.RemoveAll(p => p.Id == id);
                    product = null;
                }               
            }
            // Otherwise, add a new product
            else
            {
                var refer = _db.Products.Find(id);
                product = new Product
                {
                    Id = id,
                    Name = refer.Name,
                    Price = refer.Price,
                    Image = refer.Image,
                    Quantity = quantity
                };
                cart.Insert(0, product);
            }

            if (!Request.IsAjaxRequest())
            {
                Response.Redirect(Request.UrlReferrer.ToString());
                return null;
            }
            else
            {
                // Get sum price of all products
                total = cart.Sum(p => p.Quantity * p.Price);
                // Fetch the last 5 items
                var last5items = cart.Take(4).ToList();
                
                var response = new
                {
                    id = id,
                    quantity = product == null ? 0 : product.Quantity,
                    total = total,
                    size = cart.Count(),
                    items = last5items
                };
                
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CategoryController.cs
using MADIVE.ADL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using MADIVE.Models;

namespace MADIVE.Controllers
{
    public class CategoryController : Controller
    {
        MadiveContext _db = new MadiveContext();

        // GET: Category
        // /Category/
        public ActionResult Index(string name, int page = 1)
        {
            var models =
                (
                from p in _db.Products
                join c in _db.Categories on p.CategoryId equals c.Id
                where c.Name == name && p.Quantity > 0
                orderby p.Id descending
                select new ProductListViewModels
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = p.Price,
                    Image = p.Image,
                    Detail = p.Detail,
                    Description = p.Description,
                    CategoryId = p.CategoryId,
                    CategoryName = c.Name
                }).ToPagedList(page, 12);

            ViewBag.name = name;
            ViewBag.max = models.PageCount;
            ViewBag.page = models.PageNumber;
            ViewBag.url = ControllerContext.RequestContext.HttpContext.Request;

            return View(models);
        }

        /// <summary>
        /// Return category list displayed on menu
        /// </summary
        /// <returns>A partial view embbeded in shared_layout</returns>
        public ActionResult GetCategoryList()
        {
            var model = from c in _db.Categories
                         select c;

            return PartialView("~/Views/Category/_CategoryListPartial.cshtml", model);
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProductController.cs
using MADIVE.ADL;
using MADIVE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MADIVE.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        MadiveContext _db = new MadiveContext();

        public ActionResult Index(int Id)
        {
            var pqut = 0;

             var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];

            var product_in_cart = cart.Find(p => p.Id == Id);

            if(product_in_cart != null)
            {
                pqut = product_in_cart.Quantity;
            }

            // Get the item detail along with its three 
            // same-category products
            var model = _db.Products
                .Where(p => p.Id == Id)
                .Join(
                    _db.Categories,
                    p => p.CategoryId,
                    c => c.Id,
                    (p, c) => new ProductWithCategory 
                    {
                        Name = p.Name,
                        Price = p.Price,
                        Description = p.Description,
                        Detail = p.Detail,
                        Image = p.Image,
                        Id = p.Id,
                        Quantity = pqut,
                        CategoryId = c.Id,
                        CategoryName = c.Name,
                        Products = _db.Products
                            .Where( p2=> p2.Id != Id && p2.CategoryId == p.CategoryId)
                            .OrderBy(x=> Guid.NewGuid())
                            .Take(3).ToList()
                    })
                .Take(1).First();
            
            
            return View((ProductWithCategory)model);
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Product/Index.cshtml
@model MADIVE.Models.ProductWithCategory

@{
    ViewBag.Title = Model.Name;
}

<div class="main">
    <div class="wrap">
        <div class="product-page">
            <div class="product-container">
                <a href="#" class="product-close"></a>
                <div class="detail-left">
                    <div class="detail-left-wrap">
                        <div class="product-image-preview" style="background-image:url(@Model.Image)"></div>
                        <img src="@Model.Image">
                    </div>
                </div><!-- end product feature image -->
                <div class="detail-right">
                    <div class="detail-right-wrap">
                        <p class="page-list"><a href="@Url.Action("Index", "Home")">Shop</a>/<a href="@Url.Action("Index", "Category", new { name = Model.CategoryName})">@Model.CategoryName</a>/<a>@Model.Name</a></p>
                        <h1 class="product-title">@Model.Name</h1><!-- product title -->
                        <div class="product-info">
                            <span class="product-price">$<span>@Model.Price</span></span><!-- product price -->
                            <div class="product-quantity">
                                @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post))
                                {
                                    @Html.AntiForgeryToken()
                                    <input type="hidden" name="id" value="@Model.Id" />
                                    <p><button class="minus-quantity">-</button><input name="quantity" type="number" min="0" max="1000" readonly="readonly" value="@Model.Quantity" data-exist-value="@Model.Quantity" /><button class="plus-quantity">+</button></p>
                                    <div class="clear"></div>
                                    <a href="@Url.Action("AddToCart", "Cart")" class="add-to-cart"
                                       data-product-id="@Model.Id" data-product-add="Add to Cart" data-product-wait="Processing..." data-product-update="Update">@(Model.Quantity == 0 ? "Add to Cart" : "Update")</a>
                                    <input type="submit" value="@(Model.Quantity == 0 ? "Add to Cart" : "Update")" />
                                }
                            </div>
                        </div>
                        <ul class="accordion">
                            <li>
                                <input type="radio" name="info" id="desc" checked="checked" />
                                <label for="desc">Description</label>
                                <div class="product-desc"><p>@Model.Description</p></div><!-- product description -->
                            </li>
                            <li>
                                <input type="radio" name="info" id="detail" />
                                <label for="detail">Detail</label>
                                <div class="product-details"><p>@Model.Detail</p></div><!-- product detail -->
                            </li>
                        </ul>
                        <p class="product-category"><strong>Category</strong> <span><a href="@Url.Action("Index", "Category", new { name = Model.CategoryName })">@Model.CategoryName</a></span></p>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="same-category-product">
                <h1>You might also like</h1>
                <ul>
                @foreach (var product in @Model.Products)
                {
                    <li>
                        <a href="@Url.Action("Index", "Product", new { Id = product.Id })" style="background-image:url(@product.Image)">
                            <img src="@Url.Content("~/img/")pretend.png" alt="pretend"/>
                        </a>
                    </li>
                }
                </ul>
                <div class="clear"></div>
            </div>

        </div><!-- end product detail -->
        
    </div>
</div>

Views/Product/_ProductDetailPartial.cshtml
@model MADIVE.Models.ProductWithCategory

<div class="product-detail">
    <a href="#" class="product-close"></a>
    <div class="detail-left">
        <div class="detail-left-wrap">
            <div class="product-image-preview" style="background-image:url(@Model.Image)"></div>
        </div>
    </div>
    <div class="detail-right">
        <div class="detail-right-wrap">
            <p class="page-list"><a href="@Url.Action("Index", "Home")">Shop</a>/<a href="@Url.Action("Index", "Category", new { id = Model.CategoryName })">@Model.CategoryName</a>/<a>@Model.Name</a></p>
            <h1 class="product-title"></h1><!-- product title -->
            <div class="product-info">
                <span class="product-price">$<span>@Model.Price</span></span><!-- product price -->
                <div class="product-quantity">
                    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <p><button class="minus-quantity">-</button><input name="quantity" type="number" min="0" max="1000" readonly="readonly" value="@Model.Quantity" data-exist-value="@Model.Quantity" /><button class="plus-quantity">+</button></p>
                        <input type="hidden" name="id" value="@Model.Id" />
                        <div class="clear"></div>
                        <a href="@Url.Action("AddToCart", "Cart")" class="add-to-cart"
                           data-product-id="" data-product-add="Add to Cart" data-product-wait="Processing..." data-product-update="Update">Add to Cart</a>
                    }
                </div>
            </div>
            <ul class="accordion">
                <li>
                    <input type="radio" name="info" id="desc" checked="checked" />
                    <label for="desc">Description</label>
                    <div class="product-desc">@Model.Description</div><!-- product description -->
                </li>
                <li>
                    <input type="radio" name="info" id="detail" />
                    <label for="detail">Detail</label>
                    <div class="product-details">@Model.Detail</div><!-- product detail -->
                </li>
            </ul>
            <p class="product-category"><strong>Category</strong> <span><a href="@Url.Action("Index", "Category", new { id = Model.CategoryName})">@Model.CategoryName</a></span></p>
        </div>
    </div>
    <div class="clearfix"></div>
</div><!-- end product detail -->