Controllers/CartController.cs
using MADIVE.ADL;
using MADIVE.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MADIVE.Controllers
{
    public class CartController : Controller
    {
        MadiveContext _db = new MadiveContext();
      
        // GET: Cart
        // /Cart
        public ActionResult Index(int page = 1)
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];

            // Get sum price of all products
            ViewBag.totalPrice = cart.Sum(p => p.Quantity * p.Price);
            ViewBag.numOfItem = cart.Count();

            // Display just 4 items per page
            var models = cart.ToPagedList(page, 4);
            ViewBag.max = models.PageCount;
            ViewBag.page = models.PageNumber;

            return View(models);
        }

        /// <summary>
        /// Update the current items in cart when
        /// users update it
        /// </summary>
        /// <param name="id">the product id</param>
        /// <param name="quantity">the quantity of the product</param>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(int id, int quantity)
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];

            if (quantity == 0)
            {
                cart.RemoveAll(p => p.Id == id);
            }
            else
            {
                var updateItem = cart.Find(p => p.Id == id);
                updateItem.Quantity = quantity;
            }

            return Redirect(Request.UrlReferrer.ToString());
        }

        /// <summary>
        /// Display a quick preview of cart for last 5 items
        /// when users hover on the cart icon 
        /// </summary>
        /// <returns>Partial view with a list of 5 items in cart</returns>
        public ActionResult GetPreviewItemsInCart()
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>) Session["cart"];

            ViewBag.numOfItem = cart.Count();
            ViewBag.totalPrice = 0;
            foreach (var item in cart)
            {
                ViewBag.totalPrice += item.Price * item.Quantity;
            }
            
            // Return the partial view along with just 5 last items in cart
            return PartialView("~/Views/Cart/_PreviewCart.cshtml", cart.Take(4).ToList());
        }

        /// <summary>
        /// Add an item or update the existing item in Cart
        /// </summary>
        /// <param name="Id">The Id of Product</param>
        /// <param name="quantity">The number of product to add</param>
        /// <returns>Json object contains the items in cart if the request is AJAX</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                Session["cart"] = new List<Product>();
            }

            var cart = (List<Product>)Session["cart"];
            var total = 0.0;

            var product = cart.Find(p => p.Id == id);
            // Update the quantity inside the session
            // in the case the product was in cart
            if (product != null)
            {
                if(quantity > 0)
                {
                    product.Quantity = quantity;
                }
                // Remove the item from cart if the quantity = 0
                else
                {
                    cart.RemoveAll(p => p.Id == id);
                    product = null;
                }               
            }
            // Otherwise, add a new product
            else
            {
                var refer = _db.Products.Find(id);
                product = new Product
                {
                    Id = id,
                    Name = refer.Name,
                    Price = refer.Price,
                    Image = refer.Image,
                    Quantity = quantity
                };
                cart.Insert(0, product);
            }

            if (!Request.IsAjaxRequest())
            {
                Response.Redirect(Request.UrlReferrer.ToString());
                return null;
            }
            else
            {
                // Get sum price of all products
                total = cart.Sum(p => p.Quantity * p.Price);
                // Fetch the last 5 items
                var last5items = cart.Take(4).ToList();
                
                var response = new
                {
                    id = id,
                    quantity = product == null ? 0 : product.Quantity,
                    total = total,
                    size = cart.Count(),
                    items = last5items
                };
                
                return Json(response, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CheckoutController.cs
using MADIVE.ADL;
using MADIVE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MADIVE.Controllers
{
    public class CheckoutController : Controller
    {
        MadiveContext _db = new MadiveContext();

        // GET: Checkout
        // /checkout
        [Authorize]
        public ActionResult Index()
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];
            if(cart.Count() == 0)
            {
                return RedirectToAction("Index", "Cart");
            }
            else
            {   
                return View();
            }
        }

        // GET: Receipt
        // /checkout/receipt
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Receipt(CheckoutInfoModels info)
        {
            var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];

            if(ModelState.IsValid && cart.Count() > 0)
            {
                cart = (List<Product>)Session["cart"];
                ViewBag.totalPrice = cart.Sum(p => p.Price * p.Quantity);
                // Clone the all products in cart to send to view before clear it
                List<Product> clone = cart.ToList();
                // Remove all items in cart
                cart.Clear();

                return View(clone);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ProductController.cs
using MADIVE.ADL;
using MADIVE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MADIVE.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        MadiveContext _db = new MadiveContext();

        public ActionResult Index(int Id)
        {
            var pqut = 0;

             var cart = Session["cart"] == null
                ? new List<Product>()
                : (List<Product>)Session["cart"];

            var product_in_cart = cart.Find(p => p.Id == Id);

            if(product_in_cart != null)
            {
                pqut = product_in_cart.Quantity;
            }

            // Get the item detail along with its three 
            // same-category products
            var model = _db.Products
                .Where(p => p.Id == Id)
                .Join(
                    _db.Categories,
                    p => p.CategoryId,
                    c => c.Id,
                    (p, c) => new ProductWithCategory 
                    {
                        Name = p.Name,
                        Price = p.Price,
                        Description = p.Description,
                        Detail = p.Detail,
                        Image = p.Image,
                        Id = p.Id,
                        Quantity = pqut,
                        CategoryId = c.Id,
                        CategoryName = c.Name,
                        Products = _db.Products
                            .Where( p2=> p2.Id != Id && p2.CategoryId == p.CategoryId)
                            .OrderBy(x=> Guid.NewGuid())
                            .Take(3).ToList()
                    })
                .Take(1).First();
            
            
            return View((ProductWithCategory)model);
        }

        protected override void Dispose(bool disposing)
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Cart/Index.cshtml
@model IPagedList<MADIVE.Models.Product>

<body>
    @using (Html.BeginForm("Index", "Cart", FormMethod.Post, new { Id = "updatecart" }))
    { 
        <input type="hidden" name="quantity"/>
        <input type="hidden" name="id"/>
        @Html.AntiForgeryToken()
    }
    
    @if(ViewBag.max > ViewBag.page)
    {
        <a href="@Url.Action("Index", "Cart", new { page = ViewBag.page + 1 })" class="cart-next"><i class="fa fa-angle-right"></i></a>    
    }
    
    @if (ViewBag.page > 1)
    {
        <a href="@Url.Action("Index", "Cart", new { page = ViewBag.page - 1 })" class="cart-previous"><i class="fa fa-angle-left"></i></a>
    }
    
    <div class="main">
        <div class="wrap">
            @if(@ViewBag.numOfItem > 0)
            { 
            <table class="cart-view">
                <thead>
                    <tr>
                        <th class="p-thumbnail"></th>
                        <th class="p-name">Product</th>
                        <th class="p-price">Price</th>
                        <th class="p-quantity">QTY</th>
                        <th class="p-subtotal">Total</th>
                        <th class="p-remove">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                @foreach (var product in Model)
                {
                    <tr class="cart-item">
                        <!-- The thumbnail -->
                        <td class="p-thumbnail">
                            <a href="@Url.Action("index", "product", new { id = product.Id })" style="background-image:url(@product.Image)"></a>
                        </td>

                        <!-- Product Name -->
                        <td class="p-name">
                            <a href="@Url.Action("index", "product", new { id = product.Id })">@product.Name</a>
                        </td>
                        <!-- Quantity inputs -->
                        <td class="p-price">
                            <span class="amount">$&nbsp;@product.Price</span>
                        </td>
                        <!-- Quantity inputs -->
                        <td class="p-quantity">
                            <div class="quantity buttons_added">
                                <input type="button" value="-" class="minus">
                                <input type="number" name="quantity" value="@product.Quantity" data-existing-value="@product.Quantity" readonly="readonly">
                                <input type="button" value="+" class="plus">
                            </div>
                            <input type="button" value="Update" class="update-quantity blur" data-product-id="@product.Id"/>
                        </td>

                        <!-- Product subtotal -->
                        <td class="p-subtotal">
                            <span class="amount">$&nbsp;@(product.Quantity * product.Price)</span>
                        </td>
                        <!-- Remove from cart link -->
                        <td class="p-remove">
                            <a href="@Url.Action("Index", "Cart")" data-product-id="@product.Id" class="remove-item" title="Remove this item">×</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table><! -- end cart table -->
            }
            else
            {
                <h1 class="notify-fix">There is no item in cart</h1>
            }
            <div class="go-checkout @(ViewBag.numOfItem == 0 ? "no-item-to-checkout" : "")">
                <div class="wrap">
                    <div class="cart-total"><p>Subtotal <span>$@ViewBag.totalPrice</span></p>/ @ViewBag.numOfItem items</div>
                    <a href="@Url.Action("Index", "Checkout")" class="checkout-button">Checkout</a>
                    <a href="@Url.Action("index", "home")" class="continue-shopping">Continue shopping</a>@ViewBag.path
                </div>
            </div>
        </div>
    </div>
</body><!-- end main body section -->

Views/Cart/_PreviewCart.cshtml
@model IEnumerable<MADIVE.Models.Product>

<a href="@Url.Action("Index", "Cart")" class="view-cart-button">
    <i class="fa fa-shopping-cart"></i> 
    <span class="num-of-item @(ViewBag.numOfItem > 0 ? "shown" : "")">@ViewBag.numOfItem</span>
</a>

<div class="preview-cart">
    <h4 class="preview-last-items">@(ViewBag.numOfItem <= 4 ? ViewBag.numOfItem + " items in Cart" : "Last 4 of " + ViewBag.numOfItem + " items")</h4>
    <ul class="preview-items clearfix" data-refer-link="@Url.Action("Index", "Product")">
    @foreach (var product in Model)
    {
        <li>
            <a href="@Url.Action("Index", "Product", new { id = product.Id })">
                <span class="preview-image" style="background-image:url(@product.Image)"></span>
                <h6>@product.Name</h6>
                <p>Price: $@product.Price</p>
                <p>Quantity: @product.Quantity</p>
            </a>
        </li>
    }
    </ul>

    <h5><span>Subtotal</span> <strong class="preview-total-price">$@ViewBag.totalPrice</strong></h5>

    <ul class="preview-button clearfix">
        <li><a href="@Url.Action("Index", "Cart")">View Cart</a></li>
        <li><a href="@Url.Action("Index", "Checkout")">Checkout</a></li>
    </ul>
</div>

<div class="overlay2"></div>